# Generated by Django 3.1.8 on 2021-07-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='collection',
            new_name='collectionId',
        ),
    ]
